### ISSUE TITLE
Разобраться с бекапами

### ISSUE THREAD

**Issue by noggatur** [noggatur/oywo#15]
Как они работают на Heroku?

Как забирать определённые версии?

Как использовать бекапную версию в проекте?

Написать краткую инструкцию по работе с бекапами.

**Comment by velika12** [comment]
Настроила на хероку, что в 2 часа ночи каждый день будет делаться бэкап.

**Comment by velika12** [comment]
Добавила скрипт для автоматического обновления локальной базы и инструкцию в README.
